### ISSUE TITLE
Have a look at https://github.com/0xCAFEDECAF/VanBus

### ISSUE THREAD

**Issue by 0xCAFEDECAF** [morcibacsi/esp32_rmt_van_rx#7]
Hi Peter, your excellent work on the VAN bus stuff inspired me to polish and publish my own lingering project. Please have a look at https://github.com/0xCAFEDECAF/VanBus . This library can be used on any Espressif-based hardware and does not need any extra peripheral or datalink controller. I am planning to register my library with the Arduino library manager, like you also did with your esp32_rmt_van_rx and arduino_tss463_van libraries. Please have a look and be inspired!

**Comment by morcibacsi** [comment]
Hey man! You did an awesome job there! If your project would have been exist a year ago mine wouldn't come to live :D VAN bus is a pretty hard stuff as there isn't much interest in it. So it is good to see that someone else is also working on it ;) What project do you have in mind with it? What kind of car do you have? Do you think that it would take a lot of effort to also support the slow VAN bus with your library? (VAN body @ 62.5 kbps)? I also had another project in mind, to support VAN bus writing from software (so a TSS463 won't be necessary). With the RMT peripheral it is possible to generate the frames however bus arbitration logic can't be done by that method. Would it be possible to do it with interrupts? What do you think? Thanks again for your great work. Can I reference your project on my github pages? I know... I have lot of questions :D

Best regards, Peter. (You can also find me at my email address)
