### ISSUE TITLE
RMT RX buffer full

### ISSUE THREAD

**Issue by jnslsrwy** [morcibacsi/esp32_rmt_van_rx#9]
Hello there! I'd like to use your arduino library to read some stalk button events to build my own headunit. But I can't even get your monitor example to run on my ESP32 with the SN65HVD230.

The ESP kept crashing during bus activity with different error messages. When I increased the waiting time in line 35 from 5ms to 100ms the ESP stopped crashing and gave me lots of the following with ne number in brackets increasing: 

E (139224) rmt: RMT RX BUFFER FULL

**Comment by morcibacsi** [comment]
I have quite bad experience with SN65HVD230 transceivers (1-2 works reliably out of 10). I am using the example sketch (in a task) basically unmodified in my VAN-CAN bridge for years now, and apart from faulty CAN transceivers I haven't faced any issues. If you have a chance try a MCP2551 or one from the TJA1050/TJA1042 family (ESP32 can tolerate the 5V signal so for testing it is okay, but later if you want to be sure you can add a logic level shifter). Also make sure that there is no terminating resistor between the VAN lines as they aren't needed and can cause issues (some CAN shields have the 120 Ohm resistor preinstalled)

**Comment by jnslsrwy** [comment]
Ok I'll try it with the TJA1050. Then again I'm curious because I tried the SN65HVD230 with the ESP8266 and [0xCAFEDECAF](https://github.com/0xCAFEDECAF)'s lib and there it seems to work fine.

**Comment by morcibacsi** [comment]
You can also try this sketch:


```
#include <esp32_arduino_rmt_van_rx.h>
#include <esp32_rmt_van_rx.h>

TaskHandle_t VANReadDataTask;

ESP32_RMT_VAN_RX VAN_RX;

const uint8_t VAN_DATA_RX_RMT_CHANNEL = 0;
const uint8_t VAN_DATA_RX_PIN = 21;
const uint8_t VAN_DATA_RX_LED_INDICATOR_PIN = 2;

uint8_t vanMessageLength;
uint8_t vanMessage[34];

uint32_t lastMillis = 0;

void VANReadDataTaskFunction(void * parameter)
{
    VAN_RX.Init(VAN_DATA_RX_RMT_CHANNEL, VAN_DATA_RX_PIN, VAN_DATA_RX_LED_INDICATOR_PIN, VAN_LINE_LEVEL_HIGH, VAN_NETWORK_TYPE_COMFORT);
    //VAN_RX.Init(VAN_DATA_RX_RMT_CHANNEL, VAN_DATA_RX_PIN, VAN_DATA_RX_LED_INDICATOR_PIN, VAN_LINE_LEVEL_HIGH, VAN_NETWORK_TYPE_BODY);

    for (;;)
    {
        VAN_RX.Receive(&vanMessageLength, vanMessage);

        if (vanMessageLength > 0)
        {
            if(VAN_RX.IsCrcOk(vanMessage, vanMessageLength))
            {
                for (size_t i = 0; i < vanMessageLength; i++)
                {
                    if (i != vanMessageLength - 1)
                    {
                        printf("%02X ", vanMessage[i]);
                    }
                    else
                    {
                        printf("%02X", vanMessage[i]);
                    }
                }
                printf("\n");
            }
            else
            {
                printf("CRC ERROR!\n");
            }
        }
        vTaskDelay(5 / portTICK_PERIOD_MS);
    }
}

void setup()
{
    Serial.begin(500000);
    printf("ESP32 Arduino VAN bus monitor\n");

    xTaskCreatePinnedToCore(
        VANReadDataTaskFunction,        // Function to implement the task
        "VANReadDataTask",              // Name of the task
        20000,                          // Stack size in words
        NULL,                           // Task input parameter
        1,                              // Priority of the task (higher the number, higher the priority)
        &VANReadDataTask,               // Task handle.
        0);                             // Core where the task should run
}

void loop()
{
    vTaskDelay(50 / portTICK_PERIOD_MS);
}
```

**Comment by jnslsrwy** [comment]
Nice! This sketch works with both transcievers. As far as I can tell the sketch runs the code explicitly on core 0. How could this fix the issue?

**Comment by morcibacsi** [comment]
Why is this an issue for you? What are you trying to do?

**Comment by jnslsrwy** [comment]
There is no issue anymore. I'm glad that it works now. I am just trying to understand how the changes you made in the sketch made it work on my end :).

**Comment by tinwhisker** [comment]
> I have quite bad experience with SN65HVD230 transceivers (1-2 works reliably out of 10). I am using the example sketch (in a task) basically unmodified in my VAN-CAN bridge for years now, and apart from faulty CAN transceivers I haven't faced any issues. If you have a chance try a MCP2551 or one from the TJA1050/TJA1042 family (ESP32 can tolerate the 5V signal so for testing it is okay, but later if you want to be sure you can add a logic level shifter). Also make sure that there is no terminating resistor between the VAN lines as they aren't needed and can cause issues (some CAN shields have the 120 Ohm resistor preinstalled)

Just FYI - transceivers with Vio (not Vref or Split) can be fed with the MCU voltage to that pin to allow RXD/TXD voltage set. I.e. MCP2562
You still need 5v for Vcc though, but no need for a shifter at least.
